FROM node:19-alpine3.16 AS BUILD
RUN mkdir -p /usr/app
WORKDIR /usr/app
COPY package*.json ./
RUN yarn install
COPY . .
RUN npm run build:uat

FROM nginx:1.23.2-alpine
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=BUILD /usr/app/build /usr/share/nginx/html
