apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    name: mynfs
spec:
  storageClassName: manual
  capacity:
    storage: 900Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 90.110.123.999
    path: "/var/nfsshare"
